Codess-Cafe/Codess-Website

index.html
'Offers and Scholarships Bagged' changed from 'Offers and scholarships bagged' 'Average CTC' changed from 'Avg CTC'
Resolved assigned issue #26
=> Updated index.html (Numbers Speak Louder section) Issue #26

index.html
=> Update 'Apply' Section for Formatting and Terminology

index.html
=> update social links that appear on the left side of index.html

index.html, linkedin.html, medium.html, mentors.html, twitter.html, youtube.html
=> Remove cards update footer

style.css
Issue  #5 has been resolved
Space B/w Section Heading and Testimonail Cards is added 
**Before**
**After**
=> Issue #5 resolved (Space b/w section header & testimonal cards is added)

CONTRIBUTING.md, README.md
This pull request enhances the repository by adding a CONTRIBUTING.md file with comprehensive guidelines for open-source contributions and helpful commands. Additionally, it edits the README.md file to include a link to the CONTRIBUTING.md file and embeds the Codes Cafe logo GIF.
-Added CONTRIBUTING.md file with detailed guidelines for open-source contributions, including coding standards, commit message guidelines, and setting up.
-Edited README.md to include a link to the CONTRIBUTING.md file.
-Embedded the Codes Cafe logo GIF for a visually appealing README.
Contributing to open-source projects is an essential part of the developer community. By providing clear guidelines and a visual representation of the project, this pull request aims to enhance the collaboration experience for …
=> added CONTRIBUTING.md file and edited README.md file

style.css
closes #33 
[Video link of changes](https://drive.google.com/file/d/19WJU30ipKHBOB0HkxelSuyggq6_S5_9N/view?usp=share_link)
=> Closes #33

style.css
Fixes issue #25 
Before :
No hover effect on cards of What do our students say 
After  :
https://github.com/Codess-Cafe/Codess-Website/assets/89654310/b20fd83e-3369-4a98-aacf-7db3789dc6fe
=> Added hover effect on cards of "What our students say" section

style.css
Fixed the alignment issue where the social bar, text block and image were at different alignments. According to the instructions given, the text block was centered with respect to the image block and the social bar was aligned accordingly.
=> Fixed the alignment issue (Issue#10)

index.html, linkedin.html, medium.html, mentors.html, style.css, twitter.html, youtube.html
This PR updates the twitter logo everywhere on the website.
Fixes #20
##Type of change
Updated the twitter logo
Screenshots of the change
=> Fix: Changed the Twitter logo

style.css
I have made the heading "mentorship matters " responsive on small screens, it is now aligned in center. 
Here is the screenshot of my work
=> Fixed: mentorship matters heading

style.css
Previous: No hover effect on upcoming chapters cards
Now: Hover effect added
Resolves Issue https://github.com/Codess-Cafe/Codess-Website/issues/42
https://github.com/Codess-Cafe/Codess-Website/assets/96008596/5dfaa9aa-1180-4f72-a703-b34481e0bb42
=> Added hover effect on upcoming chapters cards [Issue#42]

index.html
Previous: No animation in the Mentorship Matters section
Now: Added animations-on-scroll to this section (both text and image)
Resolves Issue #61 
https://github.com/Codess-Cafe/Codess-Website/assets/96008596/61443b21-037d-4b55-998f-9c9c6a6a46c2
=> Added animation-on-scroll to the Mentorship Matters Section[Issue#61]

index.html, style.css
@VidhiBhatt01 
It's finally done 
Linked profiles of all team memebers are added
=> Linkedin Profiles are added

app.js, index.html
Previous: No counterup effect in Numbers Speak Louder Section
Now: Counterup effect in this section
Resolves Issue #64 
https://github.com/Codess-Cafe/Codess-Website/assets/96008596/34d37da2-7540-4cc7-b6bd-87eb919c198f
=> Added counterup in Numbers Speak Louder Section[Issue#64]

index.html, style.css
@Ruchip16 Ma'am, I have added the enhancement code for the FAQ section. Kindly review the code and consider merging it. Thank you for assigning this task to me.
=> Enhanced FAQ section

style.css
Added hover effect at the bottom of navbar links.
Before:
https://github.com/Codess-Cafe/Codess-Website/assets/77493105/86907553-00c1-4ec4-ab04-069ce66e0d0c
After:
https://github.com/Codess-Cafe/Codess-Website/assets/77493105/8538cd22-9781-42d3-9816-9e28b69c35a0
Closes issue #74
=> Added hover effect to navbar links

style.css
Issue No. #59 {https://github.com/Codess-Cafe/Codess-Website/issues/59}
**Before:**
**After:**
=> Issue No. Codess-Cafe#59 Fixed

index.html, style.css
Fixed Issue #12. The chapter cards were aligned in a fashion of 4 cards per row. Other issues like uneven size of boxes, proper aligning and correct rendering on smaller screens by reducing the number of cards in each row has been completed successfully. Here's an image of the new alignment:
=> Enhanced the Alignment of Chapter Cards #12

style.css
Fixed Issue #6. Added a margin to align the logo wrt to the nav bar beside it. Here's an image of the changes:
If there are any other changes required, do let me know.
=> Fixed Issue#6

style.css
fixed(#86)
before:
https://github.com/Codess-Cafe/Codess-Website/assets/138107242/c451d240-3584-4772-a792-a8c8a8561ee6
After:
https://github.com/Codess-Cafe/Codess-Website/assets/138107242/bfbe5857-9513-4201-8c35-305debea55eb
=> smooth transition of social icons(fixed#86)

style.css
Fixed the width and height of the images to make them look better in responsive too and added a border to them.
Before:
After:
=> Responsive, for Meet The Team Section

index.html, style.css
Fixed Issue #99. Brought the language icons to its original state. It was an issue of faulty use of class selector as both the mentor and lang icons div had the same class selector name. Made the changes accordingly. The animation effect has not been changed. This is an image of the updated layout:
=> Language icons reverted to its original state

style.css
Fixed Issue #102 . Added the relevant margin between the cards and the heading. This is what the current layout looks like:
=> Added margin for what students say section

style.css
Fixed Issue #100. Added a hover effect to the icons in the program offerings section. This is what it looks like:
https://github.com/Codess-Cafe/Codess-Website/assets/112744886/8276ebc1-c27e-471c-8d16-f0b0956cdd79
=> Added hover effect to the program offerings

style.css
@VidhiBhatt01 
Hover to LinkedIn Icon is added
=> Adding Hover to socail media link

style.css
Removed blur effect on hover on testimonial cards.
This is the final website : 
https://github.com/Codess-Cafe/Codess-Website/assets/96008596/9f52c625-bda8-42f1-8ea9-ae1f25d81dba
=> Testimonials card modified

mentors.html, style.css
I have fixed the responsiveness in three parts mainly the title image, the mentors page cards and the FAQ questions. Below are the images for the same:
FAQ Responsive:
Mentors Responsive:
Title-img Responsive:
=> Fixed mobile responsiveness
